services:
  apache:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./cursolaravel:/var/www/html

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_database
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"

  laravel:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    volumes:
      - ./seu_projeto:/var/www/html
    depends_on:
      - mysql
